### ISSUE TITLE
有实验的数据吗

### ISSUE THREAD

**Issue by xxllp** [StanleyLsx/text_classification_distillation#1]
不知道这块蒸馏的效果如何

**Comment by StanleyLsx** [comment]
> 不知道这块蒸馏的效果如何

还行，这个项目我是自己应付业务上的分类训练的，实验数据是业务数据。
对于数据量少、有倾斜的情况，曾经用Bert-base-ch蒸馏到CNN效果提升过2个点左右。

**Comment by xxllp** [comment]
好的   我这边cnn 90%  bert 94% 不知道是否还能有用 数据2w多

**Comment by StanleyLsx** [comment]
> 好的 我这边cnn 90% bert 94% 不知道是否还能有用 数据2w多

你可以试一试

**Comment by StanleyLsx** [comment]
> > 好的 我这边cnn 90% bert 94% 不知道是否还能有用 数据2w多
> 
> 你可以试一试
